version: '3'
services:
  activemq:
    image: webcenter/activemq:5.14.3
    hostname: activemq
    ports:
#      # mqtt
#      - "1883:1883"
#      # amqp
#      - "5672:5672"
      # ui
      - "8161:8161"
#      # stomp
#      - "61613:61613"
#      # ws
#      - "61614:61614"
    volumes: ["activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq"]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: admin
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: admin
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: jmx
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

  lesson2-message-central:
    depends_on:
      - activemq
    build:
      context: ./
      dockerfile: Dockerfile
    image: otus/dorofeev-lesson2-message-app
    ports:
      - 8080:8080

volumes:
  activemq-data: {}