server:
  port: 8080
  servlet:
    context-path: /


spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

central:
  input-queue: messaging.central

module:
  email-queue.input: messaging.service.email.input
  email-queue.status: messaging.service.email.status
  email-uuid-prefix: email

  sms-queue.input: messaging.service.sms.input
  sms-queue.status: messaging.service.sms.status
  sms-uuid-prefix: sms

  call-timeout: 10000

# loggng
logging:
  level:
    root: info