server:
  port: 8080
  servlet:
    context-path: /


spring:
  activemq:
    pool:
      enabled: true
      max-connections: 50

central:
  input-queue: messaging.central

module:
  email-queue.input: messaging.service.email.input
  email-queue.status: messaging.service.email.status
  email-uuid-prefix: email

  sms-queue.input: messaging.service.sms.input
  sms-queue.status: messaging.service.sms.status
  sms-uuid-prefix: sms

  call-timeout: 10000

# hawtio
management:
  endpoints:
    web:
      exposure:
        include: "hawtio,jolokia"
hawtio:
  authenticationEnabled: false

# loggng
logging:
  level:
    root: info