server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /

mybatis:
  config-location: classpath:META-INF/mybatis-config.xml

logging:
  level:
    root: info

spring:
  profiles:
    active: 'db-h2mem'
  application:
    name: finance-auth-service
  shardingsphere:
    props:
      sql.show: true
    datasource:
      names: ds0,ds1
    sharding:
      binding-tables: t_user
      tables:
        t_user:
          actual-data-nodes: ds${0..1}.t_user
          key-generator:
            column: id
            type: SNOWFLAKE
          tableStrategy:
            inline:
              shardingColumn: id
              algorithmExpression: t_user
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds${id % 2}

        t_session:
          actual-data-nodes: ds${0..1}.t_session
          key-generator:
            column: id
            type: SNOWFLAKE
          tableStrategy:
            inline:
              shardingColumn: id
              algorithmExpression: t_session
          database-strategy:
            standard:
              sharding-column: user_id
              precise-algorithm-class-name: ru.mdorofeev.finance.auth.repository.PreciseDatabaseShardingAlgorithm

---

spring:
  profiles: db-h2mem
  shardingsphere:
    datasource:
      ds0:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:finance-budget1
        password: finance
        type: com.zaxxer.hikari.HikariDataSource
        username: finance
      ds1:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:finance-budget2
        password: finance
        type: com.zaxxer.hikari.HikariDataSource
        username: finance
---

spring:
  profiles: db-postgres
  shardingsphere:
    datasource:
      ds0:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/finance_auth_1
        password: finance
        type: com.zaxxer.hikari.HikariDataSource
        username: finance
      ds1:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/finance_auth_2
        password: finance
        type: com.zaxxer.hikari.HikariDataSource
        username: finance