spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

amq:
  service:
    input.queue: messaging.service.sms.input
    status.queue: messaging.service.sms.status

logging:
  level:
    root: info