server:
  port: 8081
  servlet:
    context-path: /

spring:
    activemq:
      broker-url: tcp://localhost:61616
      user: karaf
      password: karaf


amq:
  service:
    queue:
      input: module.input.email

logging:
  level:
    root: info