spring:
    activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin

amq:
  service:
    input.queue: messaging.service.email.input
    status.queue: messaging.service.email.status

logging:
  level:
    root: info